apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: k8sazurecustomcontainerallowedregistries
spec:
  crd:
    spec:
      names:
        kind: K8sAzureCustomContainerAllowedRegistries
      validation:
        # Schema for the `parameters` field
        openAPIV3Schema:
          properties:
            imageRegex:
              type: string
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package k8sazurecustomcontainerallowedregistries

        violation[{"msg": msg}] {
          container := input_containers[_]
          not input_container_excluded(container.name)
          not re_match(input.parameters.imageRegex, container.image)
          msg := sprintf("Container image %v for container %v has not been allowed.", [container.image, container.name])
        }
