apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: k8scustomcontainerregistries
spec:
  crd:
    spec:
      names:
        kind: K8sCustomContainerRegistries
      validation:
        # Schema for the `parameters` field
        openAPIV3Schema:
          properties:
            imageRegex:
              type: string
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package k8scustomcontainerregistries
        
        violation[{"msg": msg}] {
            obj := input.review.object
            c := input_containers[_]
            not correct_registry(c.image)
            msg := sprintf("resource '%v/%v' container %v is not using correct registry", [obj.kind, obj.metadata.name, c.name])
        }


        correct_registry(image) {
            startswith(image, "wardaddy.azurecr.io/")
        }

        correct_registry(image) {
            startswith(image, "bloodbath.azurecr.io/")
        }

        input_containers[c] {
          c := input.review.object.spec.containers[_]
        }
        input_containers[c] {
            c := input.review.object.spec.initContainers[_]
        }
